config/routes.rb
Rails.application.routes.draw do
  get '/ping' => 'ping#ping'
  get '/install' => 'docs#install'
  get '/signout' => 'sessions#destroy', as: :signout
  
  resources :resources, path: '/resources/:table', constraints: {id: /.*/} do
    collection do
      get 'page/:page', action: :index
      post :bulk_destroy
      post :bulk_update
      get :bulk_edit
      get :import
      post :check_existence
      post :perform_import
      get :search
      get :chart
    end
    get :download, on: :member
  end
  resources :settings do
    get :values, on: :member
    get :columns, on: :collection
    post :update_advanced_search, on: :member
  end
  resources :widgets, only: %i(create update destroy)
  resources :schemas
  resources :searches
  resources :column_settings
  resources :docs, only: :index do
    get :keyboard_shortcuts, on: :collection
  end
  resource :install do
    get :setup_database_connection
  end
  resource :session, only: %i(new create destroy) do
    post :callback
    get :switch_account
  end
  resource :user, only: :show
  resource :registration, only: %i(new create) do
    post :callback
  end
  resource :account, only: %i(new create edit update) do
    post :cancel_tips, on: :member
  end
  resources :roles, except: %i(show)
  resource :dashboard, only: :show do
    get :settings
    get :bloat
  end
  resources :collaborators
  root to: 'docs#landing'
end

app/views/resources/_column_tables.slim
- column_groups.each do |columns|
  - if columns.present?
    table.table.table-condensed
      - columns.each do |name|
        tr
          th.col-md-3 title=name
            i.column_settings.fa.fa-cog data-path=column_setting_path(params[:table], column: name, view: 'show')
            = resource.column_display_name name
          == display_attribute :td, @item, name, resource

app/views/resources/_foreign_resource_input.slim
- value = value.is_a?(Sequel::Postgres::PGArray) ? value.to_a : value
- value.select!(&:present?) if value.is_a? Array
- record = foreign_resource.query.where(assoc[:primary_key] => value) if value.present?
- input_name = "#{assoc[:table]}[#{assoc[:foreign_key]}]"
.adminium-association
  - if resource.array_column? assoc[:foreign_key]
    = hidden_field_tag "#{input_name}[]" if value
    ul.multiple-records.sortable.list-inline data-input-name="#{input_name}[]"
      - if record
        - record.each do |r|
          li
            label
              input> type="checkbox" checked="checked" name="#{input_name}[]" value=r[assoc[:primary_key]]
              = foreign_resource.item_label r
  - else
    .input-group.single-record
      input.form-control readonly=true value=(foreign_resource.item_label(record&.first) || value)
      .input-group-addon
        a.clear-selection href="#"
          i.fa.fa-times-circle class=('invisible' if value.nil?)
    = hidden_field_tag input_name, value
  .input-group
    .input-group-addon Search
    input.form-control(type='search' data-autocomplete-url=search_resources_path(foreign_resource.table, primary_key: assoc[:primary_key]) autocomplete='off' placeholder="#{foreign_resource.columns(:search).map(&:to_s).map(&:humanize).join(', ').downcase}")
    .input-group-addon
      i.fa.fa-refresh.fa-spin.invisible
  ul.list-unstyled
    li

app/views/resources/_form.slim
javascript:
  columns_hash = #{resource.schema_hash.to_json.html_safe}
  adminium_column_options = #{resource.adminium_column_options.to_json.html_safe}
- if resource.columns(:form).any?
  .col-lg-8
    = form_tag @form_url, class: 'form-horizontal resource-form' do
      = hidden_field_tag '_method', 'put' if @form_method == 'put'
      = render 'form_fields', item: @item, required_constraints: true
      .form-group
        .col-sm-offset-4.col-sm-8
          = submit_tag 'Save', class: 'btn btn-primary', data: {disable_with: 'Sending...'}, name: 'then_redirect'
          '
          = submit_tag 'Save and create another', class: 'btn btn-info', data: {disable_with: 'Sending...'}, name: 'then_redirect'
          '
          = submit_tag 'Save and continue editing', class: 'btn btn-info', data: {disable_with: 'Sending...'}, name: 'then_redirect'
- else
  .alert.alert-warning
    h4 No form fields configured
    p There are no form fields configured for this resource. Click on the cog icon in the upper right corner to select the fields you want to fill in when creating a row for this table.

app/views/resources/_form_fields.slim
- resource.columns(:form).each do |name|
  .form-group
    label.control-label.col-sm-4 for="#{resource.table}_#{name}"
      - if required_constraints && resource.required_column?(name)
        abbr> title="required" *
      = resource.column_display_name name
    .col-sm-8.controls
      - if (assoc_info = resource.foreign_key?(name)) && !assoc_info[:polymorphic]
        - foreign_resource = resource_for assoc_info[:referenced_table]
        - count = foreign_resource.count_with_timeout
        - if count && count <= 25
          = belongs_to_select_tag item, foreign_resource, assoc_info
        - else
          = render 'foreign_resource_input', value: item[name], foreign_resource: foreign_resource, assoc: assoc_info
      - elsif assoc_info = resource.foreign_key_array?(name)
        - foreign_resource = resource_for assoc_info[:referenced_table]
        = render 'foreign_resource_input', value: item[name], foreign_resource: foreign_resource, assoc: assoc_info
      - elsif resource.column_type(name) == :hstore
        .hstore-edition
          = render 'hstore_row', table: resource.table, name: name, key: '_', value: nil, hidden: true
          - (item[name] || {'' => ''}).each do |key, value|
            = render 'hstore_row', table: resource.table, name: name, key: key, value: value, hidden: false
          .hstore-new-row
            .form-group
              .col-xs-1.col-xs-offset-11
                a.btn.btn-xs.btn-info title="Add a new key / value pair" +
      - else
        = input resource, item, name, required_constraints

app/views/resources/_hstore_row.slim
.hstore-row class=('hidden' if hidden)
  .form-group
    .col-xs-5
      input.form-control name="#{table}[#{name}][]" value=key
    .col-xs-6
      input.form-control name="#{table}[#{name}][]" value=value
    .col-xs-1
      a.btn.btn-xs.btn-danger title="Remove this key / value pair" &times;

app/views/resources/_items.slim
- if items.empty?
  - if @items.try(:page_count) && @current_page > @items.page_count && @items.page_count.nonzero?
    .alert.alert-warning
      h4 Warning!
      p
        == "You are looking for results on page #{@current_page}, but your query only has #{pluralize @items.page_count, 'result page'}, so there are no results on this page, but still #{pluralize @items.pagination_record_count, 'record'}."
        br
        'Try to go to the
        = link_to "first page", whitelisted_params.merge(page: 1)
        - if @items.page_count > 1
          '  or the
          = link_to "last page", whitelisted_params.merge(page: @items.page_count)
        = "."
  - else
    .alert.alert-info No records were found.
- else
  table.table-striped.table-bordered.table.items-list data-table=params[:table]
    thead.header
      tr
        - if actions_cell
          th.actions
            - if user_can?('destroy', params[:table]) || user_can?('edit', params[:table])
              input type="checkbox"
        - else
          th
        - permitted_columns.each do |name|
          = column_header_with_metadata resource, name do |table, column|
            == header_link name
            - if actions_cell
              - if resource.date_column?(name)
                i.fa.time-chart.fa-bar-chart data-type="TimeChart" title="Time chart for #{name}" data-path=generate_chart_path(name, 'TimeChart')
              - if pie_chart_column?(name)
                i.fa.time-chart.fa-pie-chart data-type="PieChart" title="Pie chart for #{name}" data-path=generate_chart_path(name, 'PieChart')
              - if resource.stat_chart_column?(name)
                i.fa.time-chart.fa-bar-chart data-type="StatChart" title="Statistics for #{name}" data-path=generate_chart_path(name, 'StatChart')
            i.column_settings.fa.fa-cog title="Column settings" data-path=column_setting_path(table, column: column, view: 'listing')

    tbody
      - items.each do |item|
        - item_pk = resource.primary_key_value item
        tr data-item-id=item_pk
          - if actions_cell
            td.actions
              - if item_pk
                = link_to resource_path(params[:table], item_pk) do
                  i.fa.fa-eye>
                - if user_can? 'edit', params[:table]
                  = link_to edit_resource_path(params[:table], item_pk) do
                    i.fa.fa-pencil>
                - if user_can? 'destroy', params[:table]
                  = link_to resource_path(params[:table], item_pk), method: :delete, data: {confirm: t('items.destroy_warning')}, title: 'Destroy' do
                    i.fa.fa-trash.text-danger>
              - if item_pk && (user_can?('destroy', params[:table]) || user_can?('update', params[:table]))
                input type="checkbox"
          - else
            - if item_pk
              td= link_to resource_path(params[:table], item_pk) do
                i.fa.fa-eye
          - permitted_columns.each do |name|
            == display_attribute :td, item, name, resource

app/views/resources/_next_previous_page.html.slim
- page_count = scope.try(:page_count)
.btn-group
  - if @current_page > 1
    = link_to url_for(whitelisted_params.merge(page: (@current_page - 1))), rel: 'tooltip', title: 'Previous page', data: {placement: 'bottom'}, class: 'btn btn-default'
      i.fa.fa-arrow-left

  - if (!page_count && @fetched_items.any?) || (page_count&.nonzero? && (@current_page < scope.page_count))
    = link_to url_for(whitelisted_params.merge(page: (@current_page + 1))), rel: 'tooltip', title: 'Next page', data: {placement: 'bottom'}, class: 'btn btn-default'
      i.fa.fa-arrow-right

- if page_count.nil? || page_count.nonzero?
  - warning_class = 'btn-danger' if page_count && @current_page > page_count
  .btn-group<
    = link_to "#", class: "btn btn-default dropdown-toggle #{warning_class}", data: {toggle: 'dropdown'} do
      - if page_count
        == page_entries_info(scope, entry_name: 'record')
      - else
        == page_entries_info_no_record_count @fetched_items, @current_page, @page_size
      span.caret<
    ul.dropdown-menu
      - if @current_page > 1
        li
          = link_to "Go to first page", whitelisted_params.merge(page: 1)
      - if page_count
        - ((@current_page - 3)..(@current_page + 3)).each do |page|
          - if page > 1 && page <= page_count && page != @current_page && (page + 1) != @current_page && (page - 1) != @current_page
            li
              = link_to "Go to page #{page}", whitelisted_params.merge(page: page)
        - if @current_page != page_count
          li
            = link_to "Go to last page (page #{page_count})", whitelisted_params.merge(page: (page_count))
          li.divider
      li.dropdown-header Rows per page
      - ([25, 50, 100, 200] + [resource.per_page]).uniq.sort.each do |per_page|
        li(class="#{'active' if resource.per_page == per_page}")
          = link_to per_page, whitelisted_params.merge(per_page: per_page)

app/views/resources/bulk_edit.html.slim
.modal-dialog
  .modal-content
    = form_tag @form_url, class: 'form-horizontal resource-form' do
      = hidden_field_tag '_method', 'put' if @form_method == 'put'
      - @record_ids.each do |record_id|
        = hidden_field_tag "record_ids[]", record_id
      .modal-header
        a.close data-dismiss="modal" ×
        h4.modal-title
          - if @item.present?
            = "Edit #{resource.human_name} ##{@item[resource.primary_key]}"
          -else
            = "Bulk Edit (#{@record_ids.length} #{params[:table].humanize} selected)"
      .modal-body
        - unless @item.present?
          .alert.alert-info
            'Fill in the inputs you want to update. All the records will have the same value.
            br
            'Leave the other inputs empty to preserve the original record values.
        = render 'form_fields', item: @item, required_constraints: false
      .modal-footer
        - submit_tag_label = @item.present? ? "Update #{params[:table].humanize} ##{@item[resource.primary_key]}" : "Update #{@record_ids.length} #{params[:table].humanize}"
        = submit_tag submit_tag_label, class: 'btn btn-primary', data: {disable_with: 'Sending...'}
    javascript:
      NullifiableInput.setup('form.resource-form input, form.resource-form textarea', true)
      EnumerateInput.setupForEdit('#bulk-edit-modal')

app/views/resources/chart.html.slim
.modal-dialog.modal-lg
  .modal-content
    .modal-header
      a.close data-dismiss="modal" ×
      h4.modal-title
        = "#{params[:type].underscore.humanize} for column #{params[:column]} "
        - if @widget
          i.fa.fa-star title="This view is on your dashboard" rel="tooltip" data-placement="right"
        - else
          i.fa.fa-star.add_widget.subtle title="Add to your dashboard" rel="tooltip" data-placement="right" data-form="#time-chart form"
    .modal-body
      - if params[:type] == 'StatChart' && %w(pg_stat_all_indexes pg_stat_statements).include?(params[:table])
        small.pull-right= link_to generate_chart_path(params[:column], 'EvolutionChart'), class: 'evolution-chart' do
          i.fa.fa-line-chart>
          ' Live evolution
      - if @missing_column
        .alert.alert-danger The column <b>#{params[:column]}</b> doesn't exist on table <b>#{params[:table]}</b>.
      - else
        = form_for Widget.new, remote: true do |t|
          = t.hidden_field :type, value: "#{params[:type]}Widget"
          = t.hidden_field :table, value: params[:table]
          = t.hidden_field :columns, value: params[:column]
          = t.hidden_field :grouping, value: params[:grouping]
          = t.hidden_field :advanced_search, value: params[:asearch] if params[:asearch].present?

        - if params[:type] == 'TimeChart'
          = select_tag 'grouping', options_for_select(TimeChartBuilder::GROUPING_OPTIONS, grouping), class: 'form-control', data: {path: generate_chart_path(params[:column], 'TimeChart')}
        hr
        #chart_div
        javascript:
          data_for_graph = #{{chart_data: @data, chart_type: params[:type], column: params[:column], grouping: grouping}.to_json.html_safe}
    .modal-footer
      .btn.btn-primary.pull-right data-dismiss="modal" Close

app/views/resources/edit.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      = navbar_toggle 'subnavbar'
      = link_to params[:table].humanize, resources_path(params[:table]), class: 'navbar-brand'
      .navbar-text= "Edit #{resource.item_label @item}"
    #subnavbar.collapse.navbar-collapse
      .btn-group
        = icon_button_link resource_path(resource.table, params[:id]), 'eye', 'Show'
        - if user_can? 'create', params[:table]
          = icon_button_link new_resource_path(table:params[:table], clone_id: params[:id]), 'copy', 'Clone'
        - if user_can? 'destroy', params[:table]
          = icon_button_link resource_path(resource.table, params[:id], redirect: 'index'), 'trash', 'Destroy', method: :delete, data: {confirm: t('items.destroy_warning')}, class: 'destroy-action'
      .navbar-right= settings_button 'Form settings'

= render 'resources/form'
= render 'resources/panels/form_settings'

app/views/resources/index.html.slim
javascript:
  columns_hash = #{resource.schema_hash.to_json.html_safe}
  adminium_column_options = #{resource.adminium_column_options.to_json.html_safe}

nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      = navbar_toggle 'subnavbar'
      a.navbar-brand= params[:table].humanize
    #subnavbar.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to schema_path(params[:table]), rel: 'tooltip', title: 'Schema', data: {placement: 'bottom'} do
            i.fa.fa-table<
        li.dropdown
          a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
            span.text-more data-content=display_search(@current_search) = params[:asearch].presence || 'All records'
            span.caret<
          ul.dropdown-menu
            - if params[:asearch].blank?
              li
                a data-toggle="modal" href="#advanced_search" New filter
              li.divider role="separator"
            - if params[:asearch].present? || @searches.any?
              li.dropdown-header Filters
            - if params[:asearch].present?
              li= link_to 'All records', whitelisted_params.merge(asearch: nil)
            - @searches.each do |search|
              - next if params[:asearch] == search.name
              li= link_to search.name, whitelisted_params.merge(asearch: search.name)
            - if @searches.any?
              li.divider role="separator"
            li.dropdown-header Current filter
            - if @widget
              li= link_to 'Remove from dashboard', widget_path(@widget), method: :delete
            - else
              li= link_to 'Add to dashboard', widgets_path(widget: {type: 'TableWidget', table: params[:table], advanced_search: params[:asearch]}), method: :post
            - if params[:asearch].present?
              li
                a data-toggle="modal" href="#advanced_search" Edit
              li
                = link_to 'Delete', search_path(params[:table], name: params[:asearch]), method: 'delete'
      - if resource.columns(:search).any?
        form.navbar-form.navbar-left
          - request.query_string.to_s.split('&').find_all(&:present?).each do |param|
            - name, value = unescape_name_value_pair param
            - next if name == 'search'
            input type="hidden" name=name value=value
          .input-group
            input.form-control#search_input> name="search" type='text' value=params[:search] placeholder="search on #{resource.columns(:search).map {|e|e.to_s.humanize}.join(', ').downcase}"
            .input-group-btn
              button.btn.btn-default>
                i.fa.fa-search
      .btn-group
        - if user_can? 'create', params[:table]
          = icon_button_link new_resource_path(table:params[:table]), 'plus', 'Create a new row', class: 'create-action'
        - if user_can? 'edit', params[:table]
          = icon_button_link '#', 'pencil', 'Edit selected rows', disabled: 'disabled', class: 'bulk-edit'
        - if user_can? 'destroy', params[:table]
          = icon_button_link '#', 'trash', 'Delete selected rows', disabled: 'disabled', class: 'bulk-destroy'
        = icon_button_link '#export', 'download', 'Export rows', data: {toggle: 'modal'}
        - if user_can? 'create', params[:table]
          = icon_button_link import_resources_path(table: params[:table]), 'upload', 'Import rows'
      .navbar-right
        => render 'next_previous_page', scope: @items
        = settings_button 'Listing settings'

- if params[:search].present? || params[:where] || params[:exclude]
  .row
    - if params[:search].present?
      .col-md-3
        .alert.alert-info.alert-dismissible
          == "Search for <i>#{h params[:search]}</i>"
          = link_to whitelisted_params.except(:search), class: 'close' do
            i.fa.fa-times
    - %i(where exclude).each do |filter|
      - if params[filter]
        - params[filter].each do |k, v|
          .col-md-3
            .alert.alert-warning.alert-dismissible
              - excluded = '<u>not</u>' if filter == :exclude
              - if resource.date_column? k.to_sym
                == "Where <i>#{grouping} #{k}</i> is #{excluded} <b>#{format_date(v).first}</b>"
              - else
                == "Where <i>#{k}</i> is #{excluded} <b>#{h v}</b>"
              = link_to params_without_filter(k, filter), class: 'close' do
                i.fa.fa-times
.content= render 'items', items: @fetched_items, actions_cell: true
= render '/resources/panels/listing_settings'
= render '/resources/panels/export'
= render '/resources/panels/advanced_search'
#column-settings.modal tabindex="-1"
#time-chart.modal tabindex="-1"
#bulk-edit-modal.modal tabindex="-1" data-remote-path=bulk_edit_resources_path(table: params[:table])
= form_tag bulk_destroy_resources_path(params[:table]), id: 'bulk-destroy-form'

app/views/resources/new.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      = navbar_toggle 'subnavbar'
      = link_to params[:table].humanize, resources_path(params[:table]), class: 'navbar-brand'
      .navbar-text
        ' New #{resource.human_name}
        - if params.key? :clone_id
          small
            == "| cloning #{link_to "#{resource.human_name} ##{params[:clone_id]}", resource_path(params[:table], params[:clone_id])}"
    #subnavbar.collapse.navbar-collapse
      .navbar-right
        a.navbar-btn.btn.btn-default data-toggle="modal" href="#settings" title="Form settings" data-placement="bottom" rel="tooltip"
          i.fa.fa-cog

= render 'resources/form'
= render 'resources/panels/form_settings'

app/views/resources/show.html.slim
javascript:
  columns_hash = #{resource.schema_hash.to_json.html_safe}
  adminium_column_options = #{resource.adminium_column_options.to_json.html_safe}

nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      = navbar_toggle 'subnavbar'
      = link_to params[:table].humanize, resources_path(params[:table]), class: 'navbar-brand'
      .navbar-text= "#{resource.human_name} ##{params[:id]}"
    #subnavbar.collapse.navbar-collapse
      .btn-group
        - if user_can? 'create', params[:table]
          = icon_button_link new_resource_path(table: params[:table]), 'plus', 'Create a new row', class: 'create-action'
          = icon_button_link new_resource_path(table: params[:table], clone_id: params[:id]), 'copy', 'Clone'
        - if user_can? 'edit', params[:table]
          = icon_button_link edit_resource_path(resource.table, params[:id]), 'pencil', 'Edit', class: 'edit-action'
        - if user_can? 'destroy', params[:table]
          = icon_button_link resource_path(resource.table, params[:id], redirect: 'index'), 'trash', 'Destroy', method: :delete, data: {confirm: t('items.destroy_warning')}, class: 'destroy-action'
      .navbar-right= settings_button 'Show settings'

.row.item-attributes data-table=params[:table] data-item-id=params[:id]
  .col-md-7
    = render 'column_tables', column_groups: [@strings_and_hstore_cols, @numbers_cols, @leftover_cols]
  .col-md-5
    = render 'column_tables', column_groups: [@pks_dates_and_times_cols, @boolean_and_blob_cols]

    - if resource.belongs_to_associations.any?
      table.table.table-condensed
        - resource.belongs_to_associations.each do |assoc|
          - next unless user_can? :show, assoc[:referenced_table]
          tr
            th title="Belongs to" = assoc[:foreign_key].to_s.humanize
            - foreign_key_value = @item[assoc[:foreign_key]]
            - if foreign_key_value
              td= display_belongs_to @item, assoc[:foreign_key], foreign_key_value, resource
            - else
              td.nilclass null

    - if @has_many_associations.any?
      table.table.table-condensed
        - @has_many_associations.each do |assoc|
          - next unless user_can? :show, assoc[:table]
          tr
            - count = resource.assoc_count @item, assoc
            - assoc_params = resource.assoc_conditions @item, assoc
            th.col-md-2
              = assoc[:table].to_s.humanize
              - if assoc[:polymorphic] || @has_many_associations.many? {|other_assoc| other_assoc[:table] == assoc[:table]}
                br
                small as #{assoc[:foreign_key].to_s.humanize}
            td
              - if count
                = link_to resources_path(assoc[:table], where: assoc_params) do
                  span.badge.badge-warning = count
            td
              - if count.nil?
                small= link_to "View associated #{assoc[:table].to_s.humanize}", resources_path(assoc[:table], where: assoc_params)
              - elsif count.nonzero?
                = display_associated_items resource, @item, assoc
                - if count > 5
                  ',
                  = link_to "...", resources_path(assoc[:table], where: assoc_params)
            td
              = link_to new_resource_path(assoc[:table], attributes: assoc_params), class: 'btn btn-mini', rel: 'tooltip', data: {placement: :left}, title: "Create a new associated #{assoc[:table].to_s.singularize.humanize}" do
                i.fa.fa-plus

= render 'resources/panels/show_settings'
#column-settings.modal tabindex="-1"

app/views/resources/time_chart.html.slim
.modal-header
  a.close data-dismiss="modal" ×
  h3
    == "Time chart for column #{params[:column]} "
    - if @widget
      i.icon-star.active title="This view is on your dashboard" rel="tooltip" data-placement="bottom"
    - else
      i.icon-star.add_widget title="Add to your dashboard" rel="tooltip" data-placement="bottom" data-form="#time-chart form"
.modal-body
  = form_for Widget.new, remote: true do |t|
    = t.hidden_field :type, value: 'TimeChartWidget'
    = t.hidden_field :table, value: params[:table]
    = t.hidden_field :columns, value: params[:column]
    = t.hidden_field :grouping, value: params[:grouping]
    = t.hidden_field :advanced_search, value: params[:asearch] if params[:asearch].present?

  = select_tag 'grouping', options_for_select(TimeChartBuilder::GROUPING_OPTIONS, grouping)
  #chart_div
  javascript:
    chart_data = #{{@data ? @data.map{|e|[e[0], e[2].to_i, e[1]]}.to_json : 'null'}}
.modal-footer
  .btn.btn-primary.pull-right data-dismiss="modal" Close
  