config/routes.rb
Rails.application.routes.draw do
  get '/ping' => 'ping#ping'
  get '/install' => 'docs#install'
  get '/signout' => 'sessions#destroy', as: :signout
  
  resources :resources, path: '/resources/:table', constraints: {id: /.*/} do
    collection do
      get 'page/:page', action: :index
      post :bulk_destroy
      post :bulk_update
      get :bulk_edit
      get :import
      post :check_existence
      post :perform_import
      get :search
      get :chart
    end
    get :download, on: :member
  end
  resources :settings do
    get :values, on: :member
    get :columns, on: :collection
    post :update_advanced_search, on: :member
  end
  resources :widgets, only: %i(create update destroy)
  resources :schemas
  resources :searches
  resources :column_settings
  resources :docs, only: :index do
    get :keyboard_shortcuts, on: :collection
  end
  resource :install do
    get :setup_database_connection
  end
  resource :session, only: %i(new create destroy) do
    post :callback
    get :switch_account
  end
  resource :user, only: :show
  resource :registration, only: %i(new create) do
    post :callback
  end
  resource :account, only: %i(new create edit update) do
    post :cancel_tips, on: :member
  end
  resources :roles, except: %i(show)
  resource :dashboard, only: :show do
    get :settings
    get :bloat
  end
  resources :collaborators
  root to: 'docs#landing'
end

app/models/role.rb
class Role < ApplicationRecord
  validates :name, presence: true
  belongs_to :account
  has_and_belongs_to_many :collaborators
  serialize :permissions, coder: JSON
  before_save :normalize_permissions

  def to_s
    name
  end

  def normalize_permissions
    self.permissions = (permissions || {}).to_h
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :require_admin
  skip_before_action :connect_to_db, except: %i(new edit)

  def index
    @roles = current_account.roles.order(:name).to_a
  end

  def new
    @role = current_account.roles.build permissions: {}
  end

  def edit
    @role = current_account.roles.find params[:id]
    render :new
  end

  def create
    @role = current_account.roles.build role_params
    if @role.save
      redirect_to roles_url, success: 'Role successfully created'
    else
      render :new
    end
  end

  def update
    @role = current_account.roles.find params[:id]
    if @role.update role_params
      redirect_to roles_url, success: 'Role successfully updated'
    else
      render :new
    end
  end

  def destroy
    @role = current_account.roles.find params[:id]
    @role.destroy!
    redirect_to roles_url, success: 'Role successfully destroyed'
  end

  private

    def role_params
      params.require(:role).permit(:name, collaborator_ids: [], permissions: {})
    end
end

app/views/roles/index.html.slim
.page-header: h3 Roles and permissions
.row
  - if @roles.present?
    .col-md-6
      table.table.table-striped.table-condensed
        tbody
          - @roles.each do |role|
            tr
              td= link_to role.name, edit_role_path(role)
              td
                = pluralize role.collaborators.count, "collaborator"
              td= link_to role_path(role), method: 'delete', data: {confirm: 'Are you sure?'} do
                i.fa.fa-trash
    .col-md-6= link_to 'Create a new role', new_role_path, class: 'btn btn-primary'
  - else
    .col-md-12
      .alert.alert-info
        h4 What is a role?
        p You probably want to share adminium with your collaborators, but you may not want them to see every tables, or edit or delete rows.
        p Create as many roles as you want for each group of users and assign one or more roles to any user.
        p= link_to 'Create your first role', new_role_path, class: 'btn btn-primary'

app/views/roles/new.html.slim
.page-header: h3== @role.new_record? ? 'New role' : "Edit role <i>#{h @role.name}</i>"
= simple_form_for @role, html: {class: 'form-vertical edit_role'} do |f|
  .row
    .col-md-6
      = f.input :name
      hr
      table.table.table-condensed.table-striped
        thead
          th colspan="2" Table name
          - %w(create read update delete).each do |action|
            th
              = check_box_tag "#{action}_all"
              label< for="#{action}_all"= action.capitalize
        tbody
          - @generic.tables.each do |table|
            tr
              td= check_box_tag 'all_actions', nil, nil, id: "all_actions_#{table}"
              td
                label for="all_actions_#{table}"= table.to_s.humanize
              - %w(create read update delete).each do |action|
                td= check_box_tag "role[permissions][#{table}][#{action}]", '1', @role.permissions[table.to_s].try(:[], action)
    .col-md-6
      - non_admin_collaborators = current_account.collaborators.where(is_administrator: false).order(:email)
      - if non_admin_collaborators.present?
        = f.association :collaborators, as: :check_boxes, collection: non_admin_collaborators.map {|collaborator|[collaborator.name, collaborator.id]}
      - else
        .form-group
          label.control-label Collaborators
        .alert.alert-warning
          - if current_account.collaborators.empty?
            p A role should be assigned to collaborators but you have not invited any yet.
          - else
            p Your collaborators are administrators of this account, thus they have all permissions on all tables and cannot be assigned a role.
          = link_to "Add a collaborator", collaborators_path, class: 'btn btn-primary'

  .form-group= f.submit class: 'btn btn-primary', data: {disable_with: 'Sending...'}