config/routes.rb
Rails.application.routes.draw do
  get '/ping' => 'ping#ping'
  get '/install' => 'docs#install'
  get '/signout' => 'sessions#destroy', as: :signout
  
  resources :resources, path: '/resources/:table', constraints: {id: /.*/} do
    collection do
      get 'page/:page', action: :index
      post :bulk_destroy
      post :bulk_update
      get :bulk_edit
      get :import
      post :check_existence
      post :perform_import
      get :search
      get :chart
    end
    get :download, on: :member
  end
  resources :settings do
    get :values, on: :member
    get :columns, on: :collection
    post :update_advanced_search, on: :member
  end
  resources :widgets, only: %i(create update destroy)
  resources :schemas
  resources :searches
  resources :column_settings
  resources :docs, only: :index do
    get :keyboard_shortcuts, on: :collection
  end
  resource :install do
    get :setup_database_connection
  end
  resource :session, only: %i(new create destroy) do
    post :callback
    get :switch_account
  end
  resource :user, only: :show
  resource :registration, only: %i(new create) do
    post :callback
  end
  resource :account, only: %i(new create edit update) do
    post :cancel_tips, on: :member
  end
  resources :roles, except: %i(show)
  resource :dashboard, only: :show do
    get :settings
    get :bloat
  end
  resources :collaborators
  root to: 'docs#landing'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :fetch_permissions

  def show
    @db_size = @generic.db_size
    @table_list = @permissions ? @permissions.map {|key, value| key if value['read']}.compact : @generic.tables
    @table_sizes = @generic.table_sizes @table_list
    @table_counts = @generic.table_counts @table_list
    @widgets = current_account.widgets
    @widgets = @widgets.find_all { |w| @table_list.include? w.table.to_sym }
    @comments = @generic.table_comments(@table_list).index_by { |r| r[:relname] }
  end

  def settings
    @settings = @generic.db['show all'].to_a
    @settings.select! {|setting| setting[:name][params[:filter]]} if params[:filter].present?
  end

  def bloat
    @rows = @generic.db[IO.read(Rails.root.join('lib', 'btree_bloat.sql'))].all
  end

  protected

  def fetch_permissions
    @permissions = current_collaborator.permissions unless admin?
  end
end

app/views/dashboards/_displayed_tip.html.slim
- if tip = current_account.displayed_next_tip
  .modal#welcome-modal tabindex="-1"
    .modal-dialog
      .modal-content
        .modal-header
          a.close data-dismiss="modal" ×
          h4.modal-title
            small TIP&nbsp;
            = t tip, scope: 'account.tips'
        .modal-body
          = render partial: "/docs/tips/#{tip}"
        .modal-footer
          .pull-left
            'One tip is displayed every day.
            = link_to 'Click here to stop.', cancel_tips_account_path(current_account), method: 'POST', remote: true, id: 'cancel_tip'
          .pull-right
            a.btn.btn-primary.btn-large data-dismiss="modal" href="" Close

app/views/dashboards/bloat.html.slim
h3 Database bloat
table.table.table-bordered
  thead
    tr
      - @rows.first.each_key do |k|
        th= k
  tbody
    - @rows.each do |row|
      tr
        - row.each_value do |v|
          td= v
- url = 'https://github.com/ioguix/pgsql-bloat-estimation/blob/master/btree/btree_bloat.sql'
p Based on #{link_to url, url, target: :blank}

app/views/dashboards/settings.html.slim
h3 Database settings
form.pull-right.form-inline
  input.form-control> type="search" placeholder="Filter by name" name="filter" value=params[:filter]
  button.btn.btn-primary Filter
- if @settings.any?
  table.table
    thead
      - @settings.first.keys.each do |name|
        th= name
    tbody
      - @settings.each do |setting|
        tr
          - setting.each_value do |value|
            td= value
- else
  .clearfix
  hr
  .alert.alert-warning No settings found for <b>#{params[:filter]}</b>.

app/views/dashboards/show.html.slim
.page-header
  .pull-right
    button.btn.btn-default title="Add a widget" rel="tooltip" data-placement="left" data-toggle="modal" href="#new_widget"
      i.fa.fa-plus-circle
  h3 Dashboard

- if @widgets.any?
  - @widgets.each_slice 2 do |slice|
    .row
      - slice.each do |widget|
        .widget.col-md-6 data-query-url=widget_query_path(widget, with_id: true) data-widget-id=widget.id class=(widget.type.underscore)
          .pull-right
            = link_to widget_path(widget), class: 'btn btn-mini', remote: true, method: :delete, data: {confirm: 'Sure ?'} do
              i.fa.fa-trash.subtle
          h4
            = link_to widget.name, widget_query_path(widget)
            '
            small.hidden
              span
              '  records
          .content
            .text-center
              i.fa.fa-spin.fa-5x.fa-spinner
- else
  .alert
    ' Add widgets using the
    button.btn.btn-default data-toggle="modal" href="#new_widget"
      i.fa.fa-plus-circle
    '  button in the top right corner.

.container
  table.table.table-striped.tables-info.table-sortable
    thead
      tr
        th
        th Table
        - if @comments.any?
          th Comments
        th Full table size
        th Table size
        th Record count
    tfoot
      tr
        td Totals
        td= "#{@table_sizes.length} tables"
        - if @comments.any?
          td
        td= number_to_human_size @table_sizes.values.sum { |e|e[1].to_i }
        td= number_to_human_size @table_sizes.values.sum { |e|e[2].to_i }
        td.total_table_count data-value='0' 0
    tbody
      - (@table_list - Generic::PG_SYSTEM_TABLES).each_with_index do |table, index|
        tr
          td
            = link_to schema_path(table), rel: 'tooltip', title: 'Schema'
              i.fa.fa-table>
            = link_to resources_path(table), rel: 'tooltip', title: 'Records'
              i.fa.fa-eye
          td= link_to table, resources_path(table)
          - if @comments.any?
            td= @comments.dig(table.to_s, :description)
          - if (sizes = @table_sizes[table.to_s])
            td data-value=sizes.second = number_to_human_size sizes.second
            td data-value=sizes.third = number_to_human_size sizes.third
          - else
            td colspan=2
          td data-value=@table_counts[table.to_s] = number_with_delimiter @table_counts[table.to_s]

  - if admin?
    = link_to "Add a new table", new_schema_path, class: "btn btn-info"
  .pull-right= "Database size #{number_to_human_size @db_size}"
  - if (@table_list & Generic::PG_SYSTEM_TABLES).any?
    hr
    p
      ' System tables:
      == Generic::PG_SYSTEM_TABLES.map {|table| link_to table, resources_path(table)}.join(' - ')
    p
      =< link_to 'Database settings', settings_dashboard_path
      |  -
      =< link_to 'Database bloat', bloat_dashboard_path

#new_widget.modal tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        a.close data-dismiss="modal" ×
        h4.modal-title New dashboard widget
      = simple_form_for Widget.new, html: {class: 'form-horizontal'} do |f|
        .modal-body
          = f.input :type, collection: Widget.widget_types, as: :radio_buttons, checked: 'TableWidget', item_wrapper_class: 'inline'
          = f.input :table, as: :select, collection: table_list
          .hidden= f.input :advanced_search, as: :select, collection: []
          .hidden= f.input :columns, as: :select, collection: []
          .hidden= f.input :grouping, collection: TimeChartBuilder::GROUPING_OPTIONS, include_blank: false
        .modal-footer
          = f.submit class: 'btn btn-primary'

= render partial: 'displayed_tip'

app/views/dashboards/statement_timeout.html.slim
.container
  h3.text-danger.text-center
    i.fa.fa-hourglass-end>
    'Database statement timeout
  p Sorry but Adminium cannot display the page you asked for right now.
  p The following SQL statement took more than 20 seconds to execute on your database and was thus canceled:
  .alert.alert-info= @exception.sql
  p This could have happened for various reasons:
  ul
    li Your database caches are cold and a simple refresh in a few instants might do the trick.
    li Your database server could be under a temporary heavy load and you might have better luck displaying this page later.
    li The page you requested triggered a SQL request that is unoptimized and could be executed faster with the necessary database indexes.
    li Your database server is constantly overloaded, maybe it's time to add more RAM or CPUs or switch to a more expensive Heroku Postgres plan.
    li The request timing out cannot be optimized for this particularly large table, unfortunately you're out of luck.