config/routes.rb
Rails.application.routes.draw do
  get '/ping' => 'ping#ping'
  get '/install' => 'docs#install'
  get '/signout' => 'sessions#destroy', as: :signout
  
  resources :resources, path: '/resources/:table', constraints: {id: /.*/} do
    collection do
      get 'page/:page', action: :index
      post :bulk_destroy
      post :bulk_update
      get :bulk_edit
      get :import
      post :check_existence
      post :perform_import
      get :search
      get :chart
    end
    get :download, on: :member
  end
  resources :settings do
    get :values, on: :member
    get :columns, on: :collection
    post :update_advanced_search, on: :member
  end
  resources :widgets, only: %i(create update destroy)
  resources :schemas
  resources :searches
  resources :column_settings
  resources :docs, only: :index do
    get :keyboard_shortcuts, on: :collection
  end
  resource :install do
    get :setup_database_connection
  end
  resource :session, only: %i(new create destroy) do
    post :callback
    get :switch_account
  end
  resource :user, only: :show
  resource :registration, only: %i(new create) do
    post :callback
  end
  resource :account, only: %i(new create edit update) do
    post :cancel_tips, on: :member
  end
  resources :roles, except: %i(show)
  resource :dashboard, only: :show do
    get :settings
    get :bloat
  end
  resources :collaborators
  root to: 'docs#landing'
end

app/models/account.rb
class Account < ApplicationRecord
  before_save :fill_adapter
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators
  has_many :roles, dependent: :destroy
  has_many :widgets, dependent: :destroy
  has_many :table_widgets, dependent: :destroy
  has_many :time_chart_widgets, dependent: :destroy
  has_many :pie_chart_widgets, dependent: :destroy
  has_many :stat_chart_widgets, dependent: :destroy
  has_many :searches, dependent: :destroy
  has_many :table_configurations, dependent: :destroy

  attribute :db_url
  validates :db_url, format: %r{((mysql2?)|(postgres(ql)?)):\/\/.*}, allow_blank: true
  validate :db_url_validation

  attr_encrypted :db_url, key: Rails.application.credentials.secret_key_base, algorithm: 'aes-256-cbc',
                          v2_gcm_iv: true, mode: :per_attribute_iv_and_salt


  TIPS = %w(basic_search editing enumerable export_import displayed_record advanced_search serialized relationships time_charts keyboard_shortcuts time_zones).freeze

  def valid_db_url?
    db_url.present?
  end

  def displayed_next_tip
    return unless tips_opt_in
    tips = ['welcome'] + Account::TIPS
    return unless last_tip_at.nil? || last_tip_at < 1.day.ago
    tip = tips[(tips.index(last_tip_identifier) || -1) + 1]
    update! last_tip_at: Time.current, last_tip_identifier: tip
    tip
  end

  def table_configuration_for table
    table_configurations.find_or_create_by! table: table
  end

  private

  def db_url_validation
    return if db_url.blank? || errors[:db_url].any?
    generic = Generic.new self
    generic.db.test_connection
    generic.cleanup
  rescue Sequel::Error, URI::InvalidURIError => e
    errors.add :base, e.message
  end

  def fill_adapter
    self.adapter = db_url.split(':').first if db_url? && encrypted_db_url_changed?
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :require_admin
  skip_before_action :connect_to_db, :require_account

  def new; end

  def create
    account = Account.create! params.require(:account).permit(:name)
    collaborator = current_user.collaborators.create! account: account,
      user: current_user, is_administrator: true, email: current_user.email
    session[:account_id] = account.id
    session[:collaborator_id] = collaborator.id
    redirect_to dashboard_path
  end

  def edit; end

  def update
    if current_account.update(account_params)
      if params[:install]
        redirect_to dashboard_path
      else
        redirect_to edit_account_path, notice: 'Changes saved.'
      end
    else
      render :edit
    end
  end

  def cancel_tips
    current_account.tips_opt_in = false
    render json: current_account.save
  end

  private

  def account_params
    params.require(:account)
      .permit(:db_url, :application_time_zone, :database_time_zone, :per_page, :date_format, :datetime_format)
  end
end

app/views/accounts/_roles.slim
.row
  - if @account.enterprise?
    - if @roles.present?
      .col-md-6
        table.table.table-striped.table-condensed
          tbody
            - @roles.each do |role|
              tr
                td= link_to role.name, edit_role_path(role)
                td
                  = pluralize role.collaborators.count, "collaborator"
                td= link_to role_path(role), method: 'delete', data: {confirm: 'Are you sure?'} do
                  i.fa.fa-trash
      .col-md-6= link_to 'Create a new role', new_role_path, class: 'btn btn-primary'
    - else
      .col-md-12
        .alert.alert-info
          h4 What is a role ?
          p You probably want to share adminium with your collaborators, but you do not want them to see every tables, or edit or delete rows.
          p Create as many roles as you want for each group of users and assign one or more roles to any users.
          p= link_to 'Create your first role', new_role_path, class: 'btn btn-primary'
  - else
    .col-md-12= upgrade_to_enterprise_notice

app/views/accounts/edit.html.slim
.page-header
  h3 Account settings
.row
  .col-lg-8
    = simple_form_for current_account, html: {class: 'form-horizontal'} do |f|
      - if current_account.errors.any?
        .alert.alert-danger
          h4
            = pluralize current_account.errors.count, 'error'
            = " prohibited your account from being saved:"
          ul
            - current_account.errors.full_messages.each do |msg|
              li= msg
      = f.input :db_url, required: true, input_html: {title: 'Only MySQL and PostgreSQL are supported for now. Thus your db url has to be of the form postgres://user:pass@host/database or mysql://user:pass@host/database'}
      = f.input :application_time_zone, input_html: {class: 'timezone_select2'}
      = f.input :database_time_zone, input_html: {class: 'timezone_select2'}
      = f.input :per_page, input_html: { step: 25, min: 25, max: 200, type: :number },
        hint: 'number of rows displayed per page by default'
      = f.input :datetime_format, collection: datetime_display_options(kind: :datetime), include_blank: false
      = f.input :date_format, collection: datetime_display_options(kind: :date), include_blank: false
      .form-group
        .col-sm-offset-3.col-sm-9= f.button :submit, class: 'btn-primary'

app/views/accounts/new.html.slim
h2 Create a database connection

= form_for Account.new, url: account_path, html: { class: 'form-inline' } do |f|
    => f.text_field :name, class: 'form-control', placeholder: 'Database name'
    = f.submit 'Create', class: 'btn btn-primary'